-- Add new values to sale_status enum
ALTER TYPE sale_status ADD VALUE IF NOT EXISTS 'ACEITE_ENVIADO';
ALTER TYPE sale_status ADD VALUE IF NOT EXISTS 'CHAMADO_EM_ABERTO';
ALTER TYPE sale_status ADD VALUE IF NOT EXISTS 'DESCONECTADO';